"""Initial migration.

Revision ID: bd6f28098c59
Revises: 
Create Date: 2024-10-09 16:53:15.172128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6f28098c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_sheets_sheet_id'), ['sheet_id'], unique=True)

    op.create_table('gpt_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sheet_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_name_column', sa.String(length=255), nullable=True),
    sa.Column('analysis_column', sa.String(length=255), nullable=True),
    sa.Column('assistant_id', sa.String(length=255), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['google_sheet_id'], ['google_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sheet_id', sa.Integer(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=64), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('gpt_suggestions', sa.Text(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['google_sheet_id'], ['google_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpt_response_id', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gpt_response_id'], ['gpt_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpt_response_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpt_response_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('improved_text', sa.Text(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gpt_response_id'], ['gpt_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpt_response_versions')
    op.drop_table('feedbacks')
    op.drop_table('sheet_data')
    op.drop_table('gpt_responses')
    with op.batch_alter_table('google_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_sheets_sheet_id'))

    op.drop_table('google_sheets')
    # ### end Alembic commands ###
